version: "3"

services:
  talkingwithai:
    build:
      context: ./
    command: bash -c "
      python /talkingwithai/openchat/db/init_db.py && 
      python /talkingwithai/run_bot.py"
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/talkingwithai
      - TALKING_CONF=/talkingwithai/etc/config.ini
    volumes:
      -
        type: bind
        source: ./
        target: /talkingwithai

  postgres:
    image: postgres:11.7
    environment:
      - POSTGRES_PASSWORD=talkingwithai
      - POSTGRES_USER=talkingwithai
